<a href="https://colab.research.google.com/github/yuichiok/ML_DataAnalysis/blob/master/beginner_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
    ])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.7916633 , -0.01546402,  0.40672442,  0.7525867 ,  0.25945336,
         0.02792245, -0.7267941 , -0.18419   ,  0.74635935,  0.8738892 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.1475174 , 0.06581309, 0.10038444, 0.14186409, 0.0866378 ,
        0.06873135, 0.03231362, 0.05559497, 0.1409834 , 0.1601598 ]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.6775498

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2947 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1425 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1056 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0871 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0734 - accuracy: 0.9769


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0718 - accuracy: 0.9777


[0.07180512696504593, 0.9776999950408936]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.7642143e-08, 1.7035069e-09, 1.1815664e-06, 1.2245282e-05,
        1.3652074e-10, 2.7404272e-07, 1.9131937e-13, 9.9998057e-01,
        9.6877109e-08, 5.5039013e-06],
       [4.0122696e-09, 5.3069911e-05, 9.9994588e-01, 6.6004009e-07,
        2.4632660e-16, 2.4701063e-07, 3.2148366e-09, 6.6954715e-15,
        1.2571930e-07, 5.9117093e-15],
       [4.6101130e-07, 9.9749255e-01, 3.4436781e-04, 1.0646739e-05,
        5.7073692e-05, 1.0518427e-05, 1.4038534e-05, 1.7819055e-03,
        2.8623655e-04, 2.2886697e-06],
       [9.9994183e-01, 6.2849587e-10, 2.3768418e-05, 8.1496388e-08,
        1.0348355e-06, 8.1739432e-07, 1.6457419e-05, 4.5745884e-07,
        2.7272020e-07, 1.5335803e-05],
       [3.1769355e-07, 4.3440782e-11, 3.2197840e-07, 3.6891368e-10,
        9.9925691e-01, 9.6937271e-08, 3.1053596e-06, 1.7324715e-05,
        1.1716101e-06, 7.2072231e-04]], dtype=float32)>